// ff8_accessibility.h - Core header for FF8 Original PC Accessibility Mod
#pragma once

#include <windows.h>
#include <cstdint>
#include <string>

// ================================================================
// FF8 Original PC Accessibility Mod version
// Increment on every build change
// ================================================================
#define FF8OPC_VERSION "0.14.70"  // v0.14.70: World map vehicle-announce gate. Reported by tjsquires: walking on the world map produced a stream of "Unknown vehicle" announces. Log evidence (ff8_world.log 12:27:49-12:28:01) showed the byte at WM_LOCOMOTION (0x02040A5E) monotonically incrementing while on foot — 4 → 8 → 11 → 14 → 17 → 21 → 25 → 28 → 31 → 34 → 37 → 41 over ~12 seconds — which is movement-counter behavior, not a vehicle enum. The address is wrong for this FF8/FFNx build (or has shifted since the original mapping was authored). FIX: gate CheckVehicleChange's speak path on BOTH prev and new vehicle values being in the recognized set 0..4. Either endpoint outside that range suppresses the announce and writes a [VEHICLE-GATE] log line with the raw values. Environments where the byte reads correctly are unaffected — they only ever see known→known transitions. This is a mitigation, not a real fix; identifying the correct WM_LOCOMOTION address is a separate task that needs RE / Cheat Engine work and confirmed vehicle transitions for validation. Files: world_map.cpp (CheckVehicleChange body — gate added), ff8_accessibility.h (this version).

// v0.14.69: Draw result credit fix. The "Received N <Spell>" announce in battle was sometimes crediting the wrong party member (e.g. "Quistis received 4 Blizzards" when Squall actually drew). Root cause: GetLastDrawerName in battle_tts.cpp read from s_lastValidatedDrawSlot, populated by DiffMagicInventories in battle_tts_menu.inl. That diff returns the first party slot whose magic-inventory bytes differ from a turn-start snapshot, with no tie-break — so any non-drawer magic change between snapshot and "Received" (limit-break magic cost, an earlier action in the same ATB cycle, a draw-cast that bypassed stock) wins over the actual drawer. Meanwhile s_lastDrawerPartySlot, set the instant the player enters the Draw submenu and refreshed each frame it stays open, is the direct UI truth of who chose Draw, but GetLastDrawerName never read it. FIX: GetLastDrawerName now prefers s_lastDrawerPartySlot (UI signal) and falls back to s_lastValidatedDrawSlot (diff) only when the UI signal is 0xFF. Both flags are reset to 0xFF after a successful credit so a subsequent unrelated "Received" line (Mug, victory items) doesn't carry over the drawer. ValidateDrawCharacter still runs the diff and writes [DRAW-VALID] log entries unchanged so the existing audit trail is preserved; only the speak path's name source is replaced. New diagnostic line [DRAW-CREDIT] ui-slot=N diff-slot=M -> <Name> (using ui|diff fallback) emitted at every credit decision so any future mismatch between the two signals is visible in ff8_battle.log without affecting speech. Files: battle_tts.cpp (GetLastDrawerName body), ff8_accessibility.h (this version). Note: v0.14.66/67/68 are reserved in the upstream roadmap for scan-pipeline elemental affinity / status resist / active statuses; this fix takes v0.14.69 to leave that reservation intact. Aaron may renumber on merge if preferred.

// v0.14.65.3: Add a frame-count delay between async screenshot request and capture so FF8's typewriter text rendering finishes before the framebuffer is read. v0.14.65.2 BAT confirmed the path fix worked perfectly (PNG landed at 'Logs\\screenshots\\scan_234209_596_slot3_Fastitocalon.png' which Claude can read directly without manual copying), but the captured image showed the same too-early render as v0.14.65.1: stat labels visible (HP / STR DEF / INT SPI / DEX EVA) with NO numeric values rendered, plus typewriter description showing only 'Fast' and 'A fi' partial chars. Stats announce was perfect ('Strength 20. Vitality 132. Magic 56. Spirit 180. Speed 5. Luck 0. Evasion 6. Hit 0.' for Lv14 Fastitocalon). The capture was happening on the very next swap after fire #1, before FF8's typewriter could render values. FIX: extend the existing async screenshot machinery with a frame-delay counter. New static volatile int s_captureFrameDelay alongside s_captureRequested in battle_tts_screenshot.inl. HookedSwapBuffers decrements the counter each frame and only calls DoGLCapture() when it reaches 0. RequestScreenshotAsync now takes an optional frameDelay parameter (default 0 preserves v0.14.65 behavior; existing callers including the synchronous CaptureScreenshot path are unaffected). scan_tts.cpp passes 90 (≈1.5 s at 60 fps) which gives the engine ample time to draw the full description (~95 chars) plus all 6 numeric stat values. Description renders ~1.5 chars per frame = ~63 frames; stat values typically render in another ~10-15 frames, so 90 frames has comfortable margin. User won't notice the visual delay since Aaron is blind — only the diagnostic capture is being deferred. The scan UI stays open for ~6 s before any keypress (BAT log shows window opened at 23:42:09 and key 5 pressed at 23:42:15) so the delayed capture can't accidentally catch a different UI state. CaptureScreenshot (synchronous) explicitly resets s_captureFrameDelay to 0 so its 160 ms Sleep-and-poll contract is preserved — only the async path uses the delay. Files: battle_tts_screenshot.inl (s_captureFrameDelay declaration + HookedSwapBuffers counter check + CaptureScreenshot reset), battle_tts.h (RequestScreenshotAsync gets default frameDelay=0 parameter), battle_tts.cpp (RequestScreenshotAsync impl reads frameDelay and clamps negatives to 0), scan_tts.cpp (call site passes 90 + log message updated to mention the delay), ff8_accessibility.h (this version).

// v0.14.65.2: Fix the screenshot path so scan_*.png captures land in the project's Logs\\screenshots directory alongside kind4_*, poll_NEW_*, popup_time_* etc., instead of FF8.exe's CWD (Steam install dir's Screenshots folder, where Claude has no read access). BAT result: PASS. Path now lands at 'C:\\Users\\ampag\\OneDrive\\Documents\\FFVIII-Accessibility-Mod\\FF8_OriginalPC_mod\\Logs\\screenshots\\scan_234209_596_slot3_Fastitocalon.{bmp,png}'. Image content matches v0.14.65.1 (same too-early render pattern — labels visible, no values yet, typewriter partial), confirming the path fix didn't change capture timing. Same too-early issue addressed in v0.14.65.3 with the frame-delay counter. FIX: added BattleTTS::GetScreenshotDir() public accessor that returns KIND4_SCREENSHOT_DIR (file-static const char* in battle_tts_sprite.inl, only visible inside battle_tts.cpp's translation unit). scan_tts.cpp HookedScanGetText now composes the absolute path from this accessor instead of using a relative 'Screenshots\\' prefix.

// v0.14.65.1: Fix the auto-screenshot trigger that didn't fire in v0.14.65 BAT. ROOT CAUSE: I assumed sub_B687C0 fires per-frame while the scan UI is open. v0.14.65 BAT log proved otherwise — between fire #1 (window-open) and the user closing the scan window 38 seconds later, sub_B687C0 fired exactly ONCE. So my count==30 trigger was unreachable. FIX: move the screenshot trigger from the count==30 branch to inside the count==1 branch, right after OnScanPopupSpawn(). v0.14.65 stats wiring (Part A) is unchanged — BAT confirmed perfect: announced 'Strength 16. Vitality 129. Magic 50. Spirit 180. Speed 5. Luck 0. Evasion 6. Hit 0.' for Fastitocalon Lv10, matching [SCAN-CACHE] log values exactly.

// v0.14.65: Two complementary changes — Stats key 5 wired (BAT'd PASS) + auto-screenshot capture (BAT'd FAIL — trigger never fired, fixed in v0.14.65.1).

// v0.14.64: Strip SC1-PROBE and SC2-PROBE diagnostics. v0.14.63 BAT confirmed everything works correctly: 'Cast Fire'-type spell-cast banners announce again, scan announce works cleanly with no duplication, and the IsScreenActive()-based gate correctly suppresses only the rendered scan-window text. The probes were added in v0.14.60 (SC2-PROBE) and v0.14.61 (SC1-PROBE) to identify the source of the duplicate scan announcement; that work is complete. Probes were just adding log noise on every speech call, so this build removes them along with the now-unused <intrin.h> include for _ReturnAddress(). Single-channel SAPI mode from v0.14.61 STAYS in place (s_pVoice2 = nullptr in InitSAPI) — Aaron prefers it and it eliminates the simultaneous-overlap class of bugs entirely. The v0.14.60 sub_B687C0 first-fire announce trigger STAYS — it's the correct architecture. The v0.14.62/63 Hook_show_dialog gate (suppress only when ScanTTS::IsScreenActive() during battle) STAYS — it correctly suppresses scan duplicates while letting all other battle UI text through. Files: screen_reader.cpp (3 deletions — SC1-PROBE block in Speak, SC2-PROBE block in SpeakChannel2, intrin.h include), ff8_accessibility.h (this version). The Scan TTS chapter (v0.14.50-64) is now closed; next priority returns to v0.14.65+ implementing remaining Scan field queries: stats (key 5), elemental affinity (keys 6/7/8), status resist (key 9), active statuses (key 0).

// v0.14.63: Narrow Hook_show_dialog battle-mode suppression to scan-active period only. v0.14.62 BAT confirmed Scan announce works perfectly with no duplications, but Aaron noticed an unintended regression: the 'Cast Fire'-type spell-cast banner that appears at the top of the screen when a character begins casting a spell stopped announcing. That banner rides on Hook_show_dialog (universal text renderer), and v0.14.62's blanket 'mode == 3 → suppress' gate silenced it along with the scan duplicate. Fix: narrow the suppression gate from 'currentMode == 3' to 'currentMode == 3 && ScanTTS::IsScreenActive()'. ScanTTS::IsScreenActive() returns true only between OnScanPopupSpawn (first sub_B687C0 fire — when the scan window actually renders) and OnScanPopupDespawn (when the player dismisses it). During that period — and only that period — the rendered scan text would duplicate the scan_tts.cpp auto-announce, so we suppress. Outside that period (including all other battle moments), 'Cast Fire' / 'Cast Cure' / 'Cast Scan' / mid-battle cutscene dialog / any other battle window text speaks normally through show_dialog. Sequencing safety: HookedScanGetText sets s_scanScreenActiveSlot via InterlockedExchange BEFORE returning the text to the engine, and Hook_show_dialog reads window text AFTER calling the original (which is what triggers sub_B687C0 internally). So by the time we check IsScreenActive() in show_dialog's speak path, the flag is already set on the first scan render — the very first show_dialog call for the scan window correctly suppresses. Files: field_dialog.cpp (added ScanTTS forward decl + replaced v0.14.62 gate with IsScreenActive() gate), ff8_accessibility.h (this version). The v0.10.112 'Received <item>' draw-result rewrite ('Squall received 4 Blizzards') still applies and is now permitted always in battle since it never coincides with scan being active. Note that the v0.14.62 'isDrawReceived' bypass flag is no longer needed and was removed; the rewrite logic above the gate stays in place. SC1-PROBE and SC2-PROBE diagnostic instrumentation kept active for v0.14.63 BAT verification; will strip in v0.14.64 once Aaron confirms both scan AND 'Cast Fire' work cleanly. Single-channel SAPI mode also stays.

// v0.14.62: Gate Hook_show_dialog speak path to non-battle modes only. v0.14.61 BAT (single-channel SAPI + SC1-PROBE) proved Aaron heard the duplicate twice but serialized instead of simultaneous — single-channel worked as expected. The SC1-PROBE caught THREE Voice 1 calls at the exact moment of the Scan announce: caller=0x6DC65684 (the char* Speak wrapper), all queue-mode (interrupt=0), with content matching the three text sections of the FF8 Scan UI window: 'A fish that swims in the ground...' (description), 'Fastitocalon' (name), 'LEVEL 14 HP ?????/?????' (stats line with hidden-HP markers). Source identified: Hook_show_dialog in src/field_dialog.cpp. The hook intercepts the universal text renderer at FF8Addresses::show_dialog_addr (per the v04.17 comment, hooked for MODE_TUTO coverage) and decodes any new window text into ScreenReader::Speak via the queue-mode path. ScanTTS already owns scan-window announces via the v0.14.60 architecture (sub_B687C0 first-fire — the same engine call that triggers the rendered text fetch); this hook re-speaks those same text fetches as separate utterances. Fix: in the speak path of Hook_show_dialog, when currentMode == 3 (battle), suppress the speak unless decoded text matches the v0.10.112 'Received <item>' draw-result path (which is still valid because that's a battle-specific feature owned by field_dialog, not ScanTTS). All other battle window text is silently dropped (still logged as [SHOW_DIALOG-SUPPRESS] for diagnostic auditing). Trade-off: any other battle UI text that PREVIOUSLY relied on this hook (e.g. battle dialog windows from cutscenes that play during fights) will go silent until we explicitly route them through BattleTTS. Acceptable risk — we'll catch missing announces during regression and add explicit handling. Files: field_dialog.cpp (gate), ff8_accessibility.h (version). SC1-PROBE and SC2-PROBE diagnostic instrumentation kept active for v0.14.62 BAT verification; will strip in v0.14.63 once the duplicate is confirmed gone. v0.14.61 single-channel mode also kept — separate concern from the duplicate source, but Aaron has confirmed he prefers single-channel regardless.

// v0.14.61: Single-channel SAPI mode + SC1-PROBE diagnostic. v0.14.60 BAT showed Aaron still heard simultaneous duplicate speech during Scan announce, sounding 'disjointed and difficult to follow.' The [SC2-PROBE] caught only ONE SpeakChannel2 call (caller=0x6DC8E281, the scan_tts.cpp auto-announce path), so the second voice MUST be coming through ScreenReader::Speak() — which routes to s_pVoice (voice 1) and was NOT being probed. Aaron noted he'd thought we had disabled the dual-channel audio system, but s_pVoice2 was still being created unconditionally in InitSAPI. Two changes: (1) InitSAPI now leaves s_pVoice2 = nullptr and skips its SpMMAudioOut allocation. SpeakChannel2 falls back to s_pVoice (voice 1) so all speech goes through one voice and SAPI's per-voice queue serializes everything — no simultaneous overlap is mechanically possible. Trade-off: SpeakChannel2(text, interrupt=true) now purges voice 1's queue, potentially cutting off menu/command speech mid-utterance. Aaron has confirmed he prefers this over overlapping speech. (2) Added SC1-PROBE in ScreenReader::Speak(const wchar_t*, bool) mirroring the SC2-PROBE pattern: logs caller _ReturnAddress() and 75-char text preview as [SC1-PROBE] in ff8_mod.log every call. With single-channel mode active, simultaneous overlap can't occur, but the SC1-PROBE will tell us WHICH path was redundantly speaking the scan announce on voice 1 (and let us fix the duplicate at its source in v0.14.62). Files: screen_reader.cpp (skip voice 2 creation + SC1-PROBE in Speak), ff8_accessibility.h (this version). Strip both probes in v0.14.62+ once root cause is found. Note that v0.14.60's architectural fix (announce trigger on sub_B687C0 first-fire) IS still in place and working correctly (single SC2-PROBE confirmed the auto-announce content is correct); v0.14.61 just prevents whatever is calling Speak() with the same/related text from doubling up audibly.

// v0.14.60: Architectural fix for the v0.14.59 duplicate-announce bug + cosmetic + diagnostic. v0.14.59 BAT proved the architecture fired the auto-announce at action-commit time (when the kind=0x06 val=50 popup spawns), about 9 seconds before the actual Scan UI window opens visually. Aaron heard the announce TWICE: once at start of cast animation (full content), once when the window appeared (just name+description). The mod log AudioDucker showed two distinct duck windows (19:36:33-39 and 19:36:42-47); the second has no corresponding [SCAN-TTS] Auto-announce log line, so its source is unknown as of v0.14.59 BAT review. v0.14.60 architecture: (1) MOVED announce trigger from popup-spawn (SPRITE-POLL NEW kind=0x06 val=50 in screenshot.inl) to FIRST FIRE of sub_B687C0 hook in scan_tts.cpp — sub_B687C0 fires when the engine actually reads scan text for the UI render, matching what the player sees on screen. (2) Per-scan reset of s_scanHookFireCount in OnScanCast(_, true) so 'first fire' means 'first fire of THIS scan event,' not the cumulative count across all scans this battle. HookedScanGetText now calls OnScanPopupSpawn on count==1 (instead of being a vestigial no-op); subsequent fires are throttled diagnostic-only. (3) screenshot.inl SPRITE-POLL NEW path no longer calls OnScanPopupSpawn; the comment explains the move. The DESPAWN edge still calls OnScanPopupDespawn because the popup record stays alive for the full UI session and only despawns when the player dismisses the window. (4) Cosmetic: BuildAutoAnnounce now strips trailing periods (and trailing whitespace) from the description before appending its own period, fixing the 'may be a shark.. Press number keys' double-period in v0.14.59 BAT. (5) Diagnostic: ScreenReader::SpeakChannel2(const wchar_t*) logs every call with caller _ReturnAddress() and a 75-char text preview as [SC2-PROBE] in ff8_mod.log. If v0.14.60 BAT still shows two AudioDucker duck windows during a Scan, the SC2-PROBE log lines will identify the second caller's return address (which can be mapped back to source by subtracting the dinput8.dll load base). Strip the probe in v0.14.61+ once the second caller is identified or the duplicate disappears. Files: scan_tts.cpp (architecture + cosmetic), battle_tts_screenshot.inl (remove popup-spawn trigger), screen_reader.cpp (SC2-PROBE), ff8_accessibility.h (this version). The magicId==39 fallback in ewm.inl is kept as defense-in-depth — in the new architecture it just re-arms the snapshot/counter (idempotent if popup-hook path beat it) and the next sub_B687C0 fire announces. Doomtrain Scan-effect remains a known limitation if it doesn't trigger sub_48D200 popup hook AND doesn't trigger sub_B687C0 — not yet observed.

// v0.14.59: Scan UX redesign — silent action-layer + screen-open auto-announce + interactive number-key queries 1..0 (1..4 wired this build, 5..0 stub 'Not implemented yet.' for v0.14.60..63 chapter). The action-layer (popup hook in noeffect.inl, magicId==39 in ewm.inl) silently captures a per-slot ScanSnapshot {name, level, HP, monster_id, description} and sets s_pendingScanSlot — NO speech. One frame later, the [SPRITE-POLL] NEW emitter in screenshot.inl detects the kind=0x06 val=50 popup record and calls ScanTTS::OnScanPopupSpawn, which speaks '<Name>. <Description>. Press number keys 1 through 0 for details.' on Channel 2 and sets s_scanScreenActiveSlot. While the screen is active, PollHPCheckKeys in battle_tts_hp.inl routes 1..0 to ScanTTS::SpeakField for live querying. On popup despawn, OnScanPopupDespawn clears s_scanScreenActiveSlot. v0.14.60 supersedes the announce-trigger location (see above).

// v0.14.57: Suppress duplicate Scan announcements. v0.14.56 BAT confirmed the spurious 'No effect on <target>' is gone, but Aaron heard the Scan announcement TWICE per cast: once at action-commit (popup-based action-layer) and once 10 seconds later when the Scan UI opened and triggered the dispatcher hook. Fix: two-tier dedup. Added `bool fromActionLayer = false` parameter to OnScanCast. The two action-layer callers (popup path in noeffect.inl, magicId==39 path in ewm.inl) pass true. When OnScanCast announces with fromActionLayer=true, it sets a (slot, tick) lock for 30 seconds. Hook callers (HookedScanDispatch + HookedScanGetText, both default false) check the lock at function entry. Lock is per-slot; bypassed by action-layer. BAT PASS 2026-04-29 23:38: three Scans → three announcements. Five files: scan_tts.h, scan_tts.cpp, battle_tts.cpp, battle_tts_ewm.inl, battle_tts_noeffect.inl.

// v0.14.56: Fix v0.14.55 LNK2019 by removing the duplicate ScanTTS forward declaration from battle_tts_noeffect.inl. Cross-namespace forward decls inside .inl files create nested-namespace symbols (BattleTTS::ScanTTS::OnScanCast) different from the global ::ScanTTS::OnScanCast. Fix: removed the redundant forward decl. The global declaration already exists in battle_tts.cpp at file scope.

// v0.14.55: Action-layer Scan detection via the existing popup hook (HookedPopupSprite, sub_48D200). v0.14.54 BAT proved that BOTH sub_B687C0 and sub_84F860 only fire for the FULL Scan view (first scan of a target in a battle): the dispatcher counter reached only ~120-179 fires total despite Aaron casting Scan multiple times — i.e. only ONE Scan UI session triggered hooks. The compacted/reduced view shown on repeat Scans skips BOTH window-rendering paths entirely. Fix: detect Scan one level above the UI — at the action-commit popup. Every Scan cast (regardless of view path) spawns the spell-name popup with text_id=0x06 and value=0x32 (spell ID 50 = Scan) just before sub_48E830's snapshot recorder runs. battle_tts_sprite.inl now writes `s_lastScanCastTick` whenever that popup fires; battle_tts_noeffect.inl's NoEffect_RecordSnapshot reads it at the top: if a Scan-cast tick is within 1000 ms, the snapshot is skipped (no spurious 'No effect') and ScanTTS::OnScanCast(targetSlot) is called directly to announce. OnScanCast's existing (slot, ~2 s quiet window) dedup ensures the new path doesn't double-announce when the v0.14.54 dispatcher hook also fires on full views. The dispatcher and text-fetch hooks remain in place as defense-in-depth and to provide independent detection paths. Three files touched: battle_tts_sprite.inl (s_lastScanCastTick write site in HookedPopupSprite), battle_tts_noeffect.inl (forward decl + read + skip in NoEffect_RecordSnapshot), ff8_accessibility.h (version). v0.14.55 BUILD FAILED with LNK2019 — namespace mistake on the forward declaration. v0.14.56 fixes it.

// v0.14.54: Second Scan-detection hook on sub_84F860 (the Scan UI phase dispatcher at 0x0084F860) to catch the compacted view shown on repeat Scans of the same target in a battle. v0.14.53 BAT (with the diagnostic logging) proved the v0.14.52 sub_B687C0 hook only catches the FULL Scan view: `[SCAN-HOOK] fire #1 slot=3` appeared once at 21:38:14 for the first Bite Bug cast, then never again — the second Bite Bug Scan at ~21:38:38 (compacted view, same target) skipped sub_B687C0 entirely, leading to a spurious `[NOEFFECT-FLUSH] No effect on Bite Bug` at 21:38:48. Aaron's hint confirmed: FF8 shows a compacted/reduced-info view when scanning the same target a second+ time in a battle, and that view doesn't fetch the description text. Fix: hook sub_84F860 in addition to sub_B687C0. v0.14.55 BAT showed THIS hook also doesn't fire for compacted view, requiring the action-layer fix above. The dual hooks remain installed for defense-in-depth and full-view detection.

// v0.14.53: Diagnostic build to find why Magic-menu Scan still triggers spurious 'No effect on <target>' under v0.14.52. v0.14.52 BAT installed the sub_B687C0 hook cleanly (trampoline at 0x13160F60, log line confirms 'OK') but the Magic-menu Scan on Bite Bug 1 at 21:22:17 still produced 'No effect on Bite Bug 1' — no [SCAN-TTS] Cast line between the watchdog snapshot and the flush. Two possibilities: (a) hook never fires for Magic-menu Scan because that path uses a different rendering function, OR (b) hook fires but OnScanCast silently dedups. This build adds logging to disambiguate: HookedScanGetText logs the first call and every 60th thereafter as `[SCAN-HOOK] sub_B687C0 fire #N slot=N`, and OnScanCast logs `[SCAN-DEDUP] OnScanCast suppressed slot=N` when dedup blocks. After BAT, if [SCAN-HOOK] lines appear during Magic-menu Scan, we know the hook fires and the issue is dedup; if none appear, the hook never fires for that path and we need a different signal (likely hook a different function in the Scan UI rendering chain). One file: scan_tts.cpp (diagnostic instrumentation only — no behavior change beyond logging).

// v0.14.52: Path-agnostic Scan detection via MinHook on scan_get_text_sub_B687C0 (0x00B687C0). v0.14.51 BAT proved the magicId==39 polling detection in PollBattleMagicId only fires for Draw-Cast Scans because Magic-menu Scan goes through a different effect dispatcher that doesn't write to battle_magic_id at 0x01D99A68. Aaron cast Scan 6 times (3 enemy via Draw-Cast, 3 ally via Magic menu); only the Draw-Cast cases produced [SCAN-TTS] Cast lines and worked. The five Magic-menu Scans (one enemy at 19:54:53 + three party + one missed) each got the spurious 'No effect on <target>' watchdog announcement because OnScanCast (and therefore the watchdog cancel) never fired. Fix: hook scan_get_text_sub_B687C0 — the FFNx-named Scan-text-fetch function the engine calls every render frame the Scan UI is open. It fires for ALL Scan casts regardless of cast path because every Scan UI rendering goes through it. Slot is arg[0]. Added MinHook include + hook scaffold + InstallScanGetTextHook to scan_tts.cpp; called from ScanTTS::Initialize(). Added (slot, ~2 s quiet window) dedup to OnScanCast so the per-frame hook fires (60+ Hz during UI open) only announce once per cast: announces on slot change OR after a quiet gap; same-slot fires within the gap are suppressed. The magicId==39 path in PollBattleMagicId is retained as a parallel detection — dedup makes it a no-op when the hook fired first. Two files: scan_tts.cpp (hook + dedup), ff8_accessibility.h (version).

// v0.14.51: Scan TTS spurious 'No effect on <target>' suppression. v0.14.50 BAT proved Scan announcement worked correctly ('Glacial Eye. Level 9. HP 265 of 265.' at 19:14:37) but at 19:14:42 the no-effect watchdog from battle_tts_noeffect.inl queued 'No effect on Glacial Eye.' and flushed it 10 s later — same root cause as the v0.14.49 Draw-Stock bug: Scan goes through the player-magic action-announce path (sub_48E830 retaddr=0x0048594E, arg[1]=0x16) which records a watchdog snapshot, but Scan deals no HP / status / display change BY DESIGN (it just opens an info window). Fix: new public BattleTTS::CancelNoEffectWatchdogForSlot(int) wrapping a static NoEffect_CancelForSlot helper in battle_tts_noeffect.inl that clears both s_pendingSpellNoEffect (snapshot stage) and s_pendingNoEffectAnnounce (already-queued stage) for the given slot. ScanTTS::OnScanCast calls it after SpeakChannel2 so the genuine Scan announcement fires and the watchdog stays silent. Timing analysis: PollBattleMagicId (where ScanTTS detection runs) executes BEFORE PollPendingSpellNoEffect in the same Update tick, so the cancel is always applied before the watchdog could ever expire. The defensive queued-announcement clear covers the corner case where effect 39 is written several ticks after the snapshot. Three files touched: battle_tts_noeffect.inl (new helper), battle_tts.h + battle_tts.cpp (public wrapper), scan_tts.cpp (call site + Initialize log update).

// v0.14.50: Scan spell TTS — first slice. Detection in PollBattleMagicId (battle_tts_ewm.inl): when battle_magic_id transitions to 39 (FF8BattleEffect::Scan, confirmed via FFNx canary), read the active battle target bitmask at 0x01D76884, resolve to slot via BitmaskToSlot, and announce '<Name>. Level <L>. HP <cur> of <max>.' on Channel 2 via BattleSpeakEvent. Soft fallback: when maxHP > 99,999, announce 'HP unknown' instead — wiki guidance for hidden-HP enemies. Exact engine mechanism (whitelist vs numeric) deferred to v0.14.53; for now any max > 99,999 hides the value. No new files; ~30 lines added inside PollBattleMagicId reusing existing helpers (GetSlotName, BitmaskToSlot, BattleSpeakEvent) and entity-struct offset constants. Description, elemental affinities, status resists, and repeat-spam suppression are upcoming slices v0.14.51..v0.14.53. Deep research findings at Plan & Research Documents/Scan spell deep research results.md.

// v0.14.49: Draw-Stock no-effect suppression. The watchdog in battle_tts_noeffect.inl was firing 'No effect on <enemy>' ~6 s after every Draw > Target > Spell > Stock action because Stock genuinely doesn't change HP, status, or any of the watchdog's monitored signals. Draw > Cast must keep the watchdog active (a Fire-absorbing enemy castled with Fire is a genuine no-effect case that should announce). Fix: at the top of NoEffect_RecordSnapshot, gate on s_submenuCommandId == 0x16 (Draw command was selected during this turn's submenu nav) AND the live byte at 0x01D768D9 == 0 (Stock cursor, not Cast). Both conditions must be true to skip the snapshot. s_submenuCommandId persists across the turn-end -> action-execute transition because PollTurnAndCommands only resets it on the NEXT turn's start, so it's still valid when sub_48E830 fires for the Draw action. We don't add s_inSubmenu to the gate because that flag IS cleared on activeChar -> 0xFF before sub_48E830 fires. The live byte at 0x01D768D9 is read fresh every time rather than falling back on s_drawStockCastPrev (which could be 0xFF if the player confirmed Stock at default cursor without ever moving). One-file change in src/battle_tts_noeffect.inl plus this version bump.

// v0.14.48: Audio ducking tuning pass after v0.14.47 BAT. Three changes per Aaron's listening: (1) hold time 200ms -> 800ms on both buses to bridge gaps between menu-nav announcements (the v0.14.47 200ms hold was just short enough that volume bounced up between successive menu cursor moves). (2) BGM depth -15 dB -> -10 dB; v0.14.47 BGM duck was deeper than necessary now that ducking is working at all. (3) SFX depth -6 dB -> -15 dB; attack animation SFX still masked TTS at -6 dB, so escalated to match the depth that was previously on BGM. Pure constant changes in GameAudio::Initialize -- no architecture changes.

// v0.14.47: Audio ducking Phase 2 — reusable AudioDucker module with per-bus configuration (BGM and SFX), reference-counted BeginDuck/EndDuck trigger, smoothed one-pole envelope (separate attack/release time constants), hold timer to bridge SAPI chunk gaps, and dB-based config converted to linear gain internally. New files: src/audio_ducker.h + audio_ducker.cpp. Wired into game_audio.cpp via four function-pointer accessors (GetUserBgmVolume / ApplyBgmVolume / GetUserSfxVolume / ApplySfxVolume) so the ducker stays domain-agnostic. GameAudio::Update polls ScreenReader::IsSpeaking() once per tick on the rising/falling edge to drive BeginDuck / EndDuck; existing 500ms periodic Reapply gates on !AudioDucker::IsActive(); F2 toggle now actually switches ducking on/off via AudioDucker::SetEnabled. Default depths: BGM -15 dB (deep — GF summon music masks AD heavily), SFX -6 dB (light — most SFX short). Default times: 100 ms attack, 600 ms release, 200 ms hold. dB depths hardcoded for now because Config::GetInt uses GetPrivateProfileInt which doesn't handle negative-value INI keys cleanly — tunable in source. F5/F6/F7/F8 volume changes skip the immediate Reapply call when ducker is active so they don't briefly flash to user-level mid-duck (ducker picks up the new user vol on next Tick).

// v0.14.45: SFX volume control + audio-ducking toggle + full keyboard layout reshuffle. Resolved game-side sfx_set_master_volume via opcode_effectplay2 chain (pExecuteOpcodeTable[0x21] -> +0x5F sfx_play_to_current_playing_channel -> +0x35 play_sfx_on_channel -> +0xA1 sfx_set_volume; sfx_get_master_volume = sfx_set_volume - 0x10; sfx_set_master_volume = sfx_get_master_volume - 0xE0). FFNx replaces sfx_set_master_volume with a JMP to its own setSFXMasterVolume bridge in the same way it replaces set_midi_volume. Mirrored the v0.09.24 BGM hook architecture: scan the FFNx replacement bytes for nxAudioEngine ptr + setSFXMasterVolume method address, MinHook the FFNx function, periodically reapply via direct __fastcall thiscall shim. New persistent INI keys: sfx_volume (default 100), tts_duck_enabled (default 1), sfx_duck_ratio (default 30, percent for hand-editability). Auto-duck logic itself is deferred to v0.14.46 — F2 toggle persists the bool and announces state but is otherwise inert until Phase 2 wires ScreenReader::IsSpeaking() polling. Keyboard layout reshuffled per Aaron: F1 cycle voice, F2 ducking toggle, F3/F4 speech rate, Shift+F3/F4 speech volume, F5/F6 SFX volume, F7/F8 BGM volume. Removed v0.12.21 stale F2 'Director Varblock' diagnostic block from field_nav_handlekeys.inl (DEVNOTES called it unused but it was firing). Generalized 'Function key repurposing rule' added to DEVNOTES.

// v0.14.44: GF summon audio descriptions. New module gf_audio_desc.cpp/h mirrors fmv_audio_desc architecture. Per-GF VTT files embedded as RCDATA resources (IDR_VTT_GF_BASE = 6000). Trigger wired into PollBattleMagicId() in battle_tts_ewm.inl: when battle_magic_id changes to a GF effect ID, GfAudioDesc::OnGFAnimationStart fires and begins cue playback on Channel 2 (event voice). Stops playback when battle_magic_id reverts (covers natural end + R1+L1 skip). VTTs cover all 16 junctioned GFs (Quezacotl, Shiva, Ifrit, Siren, Brothers, Diablos, Carbuncle, Leviathan, Pandemona, Cerberus, Alexander, Doomtrain, Bahamut, Cactuar, Tonberry, Eden) plus Phoenix (item) and Odin (auto-summon). Each opens with GF name + attack name (replaces visual popup), then cues describe animation phases. Timing draws on community references; will need BAT tuning per GF since animation durations are approximate.

// v0.14.43: Diagnostic cleanup post-Bug-A resolution. Stripped DumpItemMenuState (the [ITEM-DUMP] block) from src/battle_tts_menu.inl — v0.14.42 BAT verified the disassembly model so the dump is no longer needed. Stripped [BATTLESPEAK-DIAG] log preamble/postamble from BattleSpeak in src/battle_tts.cpp — added in v0.14.37 to investigate items audio purge, no longer needed. Stripped [SPEAK-DIAG] log statements from ScreenReader::Speak in src/screen_reader.cpp — same provenance. Net: ~150 lines of diagnostic code removed; F12 stays free for next investigation. The [ITEM-LIST] block is retained (low overhead, one shot per submenu open, useful for future regression checks). No functional changes; behavior identical to v0.14.42 with cleaner logs.

// v0.14.40: Items submenu — visual page/slot fix + comprehensive diagnostic dump. v0.14.39 BAT showed (a) FindItemControllerNode() returns NULL on every cursor read (40/40) — the v0.10.104 handler signature 0x4F81F0 isn't where expected in this build, OR FFNx replaced it, OR the pool layout shifted; (b) Aaron's saved arrangement has gaps between items ("Elixir was page 1 slot 4 when really it was on page 3 following a bunch of empty slots"). Fix part 1 (visual position): added boIdx field to BattleItemEntry tracking the original battle_order position. BuildItemList now records boIdx for each item. New GetItemVisualPos() helper computes page/slot from boIdx (so saved-arrangement gaps are reflected). Both items announce paths (main + SUBMENU-DELAYED) use it. Theory: BATTLE_SUBMENU_CURSOR is a compacted item-index cursor; engine renders items at their battle_order POSITIONS with empties preserved. Fix part 2 (diagnostic): added DumpItemMenuState() that runs once per items submenu open. Logs raw 32 bytes of battle_order, inv lookup for each non-FF entry, hex dump of all 10 pool slots first 0x40 bytes, every code-pointer DWORD found in pool memory (0x004XXXXX or 0x6E70XXXX range), explicit search for ITEM_HANDLER (0x4F81F0) at every offset, and 32 bytes around BATTLE_SUBMENU_CURSOR for cursor-neighborhood inspection.

// v0.14.39: Bug A items-ordering attempted fix via pool-node helper. BAT proved helper returns NULL across the entire battle — handler offset/address don't match this build.

// v0.14.38: Bug B fully FIXED (every damage event fired via sub_5068B0 / Flag #2). Bug A items-not-heard FIXED (false-exit suppression extended to Item submenu). Bug A new variant discovered: items announce in wrong order. Three flags codified: Flag #1 (sub_48EF80) = action-launch, NOT a trigger. Flag #2 (sub_5068B0) = damage sprite, PRIMARY. Flag #3 (anim flag 1->0) = catch-all fallback.

// v0.14.37: Bug B revert + Bug A diagnostic. v0.14.36 BAT FAILED — popup-create primary fired 1-5s before render-hook. Reverted to render-hook primary, popup-create as fallback. Added [BATTLESPEAK-DIAG] in BattleSpeak and [SPEAK-DIAG] in ScreenReader::Speak for items submenu investigation. Diagnostic logs remain in v0.14.38 and will be removed in v0.14.39.

// v0.14.36: Bug B FAILED FIX — inverted primary/fallback ordering. Made sub_48EF80 primary, sub_5068B0 fallback, both with 500ms freshness gate. BAT 22:09-22:11 showed popup-create fires 1-5s before dmg-render, every event ANIM-UP-timed. Reverted in v0.14.37.

// v0.14.35: Two-bug fix from v0.14.34 long-battle BAT. Bug A item-submenu fix retained.

// v0.14.34: Restore sprite/spell event hooks (bug 2 of 4 from v0.14.31 BAT — the actual fix).
//
// v0.14.33: Restore status-spell no-effect ALLY-already-status fallback (sub_48E830 watchdog hook — still required for cases where engine short-circuits before sub_4877F0)
//
// v0.14.32: REGRESSION FIX (bug 1 — damage announcement timing)
//
// v0.14.31: BUILD RECOVERY (linker errors)
//
// v0.14.30: BUILD RECOVERY (architectural fix — mod_forward_decls.h)
//
// v0.14.28: BUILD RECOVERY (name_bypass Mod, field_dialog/archive/navigation namespace decls)
//
// v0.14.27: BUILD RECOVERY (name_bypass forward decls — wrong function name)
//
// v0.14.26: BUILD RECOVERY (s_gdiplusToken, PollStatusChanges, menu_tts ff8_addresses include, game_audio namespace decls)
//
// v0.14.25: BUILD RECOVERY attempt 2 — restored battle_tts.cpp from GitHub HEAD + .inl includes (got most of the way; 4 errors left)
//
// v0.14.24: BUILD RECOVERY attempt 1 (failed — helpers + s_ewmEnabled fixes weren't enough)
//
// v0.14.22: Fixed spell ordering attempt (still backwards)
// v0.14.21: Auto-building scanner (worked but backwards)  
// v0.14.20: Manual spell collection proof-of-concept
#define FF8OPC_VERSION_DATE "2026-05-02"

// ============================================================================
// FF8 Runtime Address Resolution
// See ff8_addresses.h / ff8_addresses.cpp for the resolver that computes
// addresses at runtime using the same offset-chain technique as FFNx.
// ============================================================================
